Repository inbo/fistools, pull requests merged in 2024-10, with the labels that each got.

#86 Update nieuwe-functie-aanmaken.md
  .github/ISSUE_TEMPLATE/nieuwe-functie-aanmaken.md
  DESCRIPTION
Labels: documentation, enhancement

#85 NEW FUNCTION rename_ct_files
  DESCRIPTION
  NAMESPACE
  R/rename_ct_files.R
  docs/404.html
  docs/CODE_OF_CONDUCT.html
  docs/LICENSE-text.html
  docs/LICENSE.html
  docs/authors.html
  docs/index.html
  docs/pkgdown.yml
  docs/reference/CRS_extracter.html
  docs/reference/UUID_List.html
  docs/reference/apply_grtsdb.html
  docs/reference/boswachterijen.html
  docs/reference/calculate_polygon_centroid.html
  docs/reference/check.html
  docs/reference/cleanup_sqlite.html
  docs/reference/col_content_compare.html
  docs/reference/colcompare.html
  docs/reference/collect_osm_features.html
  docs/reference/download_dep_media.html
  docs/reference/download_gdrive_if_missing.html
  docs/reference/download_seq_media.html
  docs/reference/drg_example.html
  docs/reference/index.html
  docs/reference/install_sp.html
  docs/reference/label_converter.html
  docs/reference/label_selecter.html
  docs/reference/lib_crs.html
  docs/reference/rename_ct_files.html
  docs/sitemap.xml
  man/rename_ct_files.Rd
Labels: Function

#89 Update increment_version.R
  DESCRIPTION
  preprocessing/increment_version.R
Labels: bug
